// @ts-check
import { fileURLToPath } from "node:url";
import { dirname } from "node:path";

/**
 * The Content-Security-Policy is built per-request in `src/middleware.ts` so it
 * can carry a fresh nonce (`buildCsp` in `src/lib/csp.ts`). That lets production
 * drop `'unsafe-inline'` from script-src. The static security headers below
 * (X-Frame-Options, HSTS, COOP/CORP, Permissions-Policy, …) stay here.
 */

/** @type {import('next').NextConfig} */
const nextConfig = {
  // Standalone build is required for the Dockerfile copy-pattern
  // (`apps/web/.next/standalone/server.js`). It strips node_modules to
  // only the packages actually used at runtime — image goes from ~1 GB
  // down to ~180 MB.
  output: "standalone",
  reactStrictMode: true,
  poweredByHeader: false,
  // Stable in Next 15.5+ (was experimental in 15.0)
  typedRoutes: true,
  experimental: {
    optimizePackageImports: ["lucide-react", "date-fns"],
  },
  transpilePackages: [
    "@marquee/ui",
    "@marquee/core",
    "@marquee/db",
    "@marquee/cache",
    "@marquee/secrets",
    "@marquee/api-contracts",
    "@marquee/observability",
    "@marquee/email",
    "@marquee/license",
  ],
  serverExternalPackages: ["argon2", "sharp", "@node-rs/argon2", "pino", "pino-pretty", "@anthropic-ai/sdk", "openai", "@google/generative-ai"],
  productionBrowserSourceMaps: false,
  compress: true,
  // ESLint isn't wired into this workspace's build (lint runs via the root
  // flat config in CI); keep it out of `next build`. Typecheck IS enforced.
  eslint: { ignoreDuringBuilds: true },
  // Fail the build on any TypeScript error — the web package typechecks clean.
  typescript: { ignoreBuildErrors: false },
  async redirects() {
    return [
      // Browsers auto-ping /favicon.ico regardless of <link rel="icon">.
      // Our app icon is generated by app/icon.tsx — redirect the legacy
      // path to it so monitor logs stay clean.
      { source: "/favicon.ico", destination: "/icon", permanent: true },
    ];
  },
  async headers() {
    // HSTS must only be advertised when the deployment is actually served over
    // HTTPS. A self-host box on http://localhost:3000 must NOT emit
    // `Strict-Transport-Security`: browsers ignore it for `localhost`, but on
    // any other hostname reached over http it would pin the origin to https
    // with no TLS listener to answer — effectively bricking the box. We key off
    // APP_URL with the SAME predicate as `useSecureCookies()` (see
    // src/lib/cookie-security.ts) so Secure cookies and HSTS always agree.
    // A missing/unusual APP_URL in production still emits HSTS (fail-safe:
    // never silently drop a real TLS deployment's hardening).
    const httpsDeployment =
      process.env.NODE_ENV === "production" &&
      !(process.env.APP_URL ?? "").startsWith("http://");
    return [
      {
        source: "/(.*)",
        headers: [
          // Anti-framing + MIME sniffing
          { key: "X-Frame-Options", value: "DENY" },
          { key: "X-Content-Type-Options", value: "nosniff" },
          // Referrer scope
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          // Feature isolation
          {
            key: "Permissions-Policy",
            value:
              "camera=(), microphone=(), geolocation=(), interest-cohort=(), browsing-topics=(), payment=()",
          },
          // CSP is set per-request (with a nonce) in src/middleware.ts.
          // HSTS — only on an actual HTTPS deployment (see httpsDeployment above).
          ...(httpsDeployment
            ? [
                {
                  key: "Strict-Transport-Security",
                  value: "max-age=63072000; includeSubDomains; preload",
                },
              ]
            : []),
          // Spectre/Meltdown isolation for sensitive routes (cross-origin)
          { key: "Cross-Origin-Opener-Policy", value: "same-origin" },
          { key: "Cross-Origin-Resource-Policy", value: "same-origin" },
        ],
      },
      {
        // Health/status probes — cacheable for monitors, never auth-leaky
        source: "/api/v1/(healthz|readyz|status)",
        headers: [{ key: "Cache-Control", value: "public, max-age=10, s-maxage=10" }],
      },
      {
        // Static assets — long-cache (Next already fingerprints these)
        source: "/_next/static/(.*)",
        headers: [
          { key: "Cache-Control", value: "public, max-age=31536000, immutable" },
        ],
      },
    ];
  },
};

const __dirname = dirname(fileURLToPath(import.meta.url));
nextConfig.outputFileTracingRoot = `${__dirname}/../..`;

export default nextConfig;
