// @ts-check
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import reactHooks from "eslint-plugin-react-hooks";
import next from "@next/eslint-plugin-next";

export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/.next/**",
      "**/.turbo/**",
      "**/dist/**",
      "**/build/**",
      "**/coverage/**",
      "**/generated/**", // generated Prisma clients etc. — never lint generated code
      "**/prisma/migrations/**",
      "**/*.config.{js,mjs,cjs,ts}",
      // Build scripts + tests aren't in the typed `tsconfig` project, so the
      // type-aware parser can't resolve them — exclude rather than parse-error.
      "**/*.mjs",
      "**/*.test.{ts,tsx}",
      "**/*.spec.{ts,tsx}",
      "**/test/**",
      "**/tests/**",
      "**/e2e/**",
      "**/next-env.d.ts", // generated by Next; its mandatory /// reference trips triple-slash-reference
      "apps/wizard/ui/**", // plain browser JS, not part of any tsconfig project
      "apps/worker/sealed/**", // sealed-bundle build tooling, excluded from tsconfig
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // Project conventions
      "@typescript-eslint/consistent-type-imports": ["error", { prefer: "type-imports" }],
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-floating-promises": "error",
      // `attributes: false` — async JSX event handlers (onClick={async …}) are
      // idiomatic and safe in React; keep the rule for the genuinely dangerous
      // cases (promise in a conditional, passed to a void-expecting argument).
      "@typescript-eslint/no-misused-promises": ["error", { checksVoidReturn: { attributes: false } }],
      "@typescript-eslint/require-await": "warn",
      "@typescript-eslint/no-non-null-assertion": "warn",
      // Disallow raw redis.get/set — must use cacheKey helpers (tenant isolation)
      "no-restricted-syntax": [
        "error",
        {
          selector:
            "CallExpression[callee.object.name='redis'][callee.property.name=/^(get|set|del|hget|hset|incr|expire)$/] > Literal:first-child",
          message:
            "Do not use raw redis keys. Use cacheKey.X() helpers from @marquee/cache to ensure tenant isolation.",
        },
      ],
    },
  },
  {
    files: ["apps/web/**/*.{ts,tsx}"],
    plugins: { "react-hooks": reactHooks, "@next/next": next },
    rules: {
      ...reactHooks.configs.recommended.rules,
      ...next.configs["core-web-vitals"].rules,
    },
  },
  // ── Adoption calibration (eslint turned on for a mature codebase) ──────────
  // Strategy: keep HIGH-SIGNAL correctness rules as errors (they catch real
  // bugs and we fix them); downgrade the noisy "loose-types" + stylistic typed
  // rules to warnings — a visible backlog to tighten over time — so CI stays
  // green and the pre-commit hook isn't a wall on day one.
  {
    rules: {
      "@typescript-eslint/no-unsafe-assignment": "warn",
      "@typescript-eslint/no-unsafe-member-access": "warn",
      "@typescript-eslint/no-unsafe-call": "warn",
      "@typescript-eslint/no-unsafe-return": "warn",
      "@typescript-eslint/no-unsafe-argument": "warn",
      "@typescript-eslint/no-base-to-string": "warn",
      "@typescript-eslint/restrict-template-expressions": "warn",
      "@typescript-eslint/no-redundant-type-constituents": "warn",
      "@typescript-eslint/prefer-nullish-coalescing": "warn",
      // OFF (not just warn): it false-positives on Prisma `Json` columns, whose
      // `JsonValue` type needs an `as unknown as T` bridge that the rule wrongly
      // flags as unnecessary — and its autofix (which lint-staged runs on every
      // commit) silently STRIPS those casts and breaks the build. Disabled until
      // the Json fields are given precise client types.
      "@typescript-eslint/no-unnecessary-type-assertion": "off",
    },
  },
  {
    files: ["apps/web/**/*.{ts,tsx}"],
    rules: {
      // App Router has no /pages dir — this Next rule is spurious here.
      "@next/next/no-html-link-for-pages": "off",
      // react-hooks v7 compiler-era rules are noisy on existing code; keep them
      // as a backlog. rules-of-hooks stays an error (it catches real bugs).
      "react-hooks/set-state-in-effect": "warn",
      "react-hooks/purity": "warn",
      "react-hooks/immutability": "warn",
      "react-hooks/refs": "warn",
    },
  },
);
