import type { Metadata, Viewport } from "next";
import { headers } from "next/headers";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/feedback/Toaster";

/**
 * Type — Release Flight runs on ONE family: Inter (self-hosted variable font,
 * wght 100–900 + matching italic). It powers EVERY token — display/headings,
 * body/UI, the brand wordmark, and the "mono" slots (numerics/ids lean on
 * Inter's tabular figures). The variable axis means `font-variation-settings:
 * 'wght' N` on headings resolves correctly. No webfont fetch at runtime — the
 * files ship in the bundle (apps/web/src/fonts/InterVariable*.ttf), so the
 * strict production CSP is unaffected.
 */
const inter = localFont({
  src: [
    { path: "../fonts/InterVariable.ttf", weight: "100 900", style: "normal" },
    { path: "../fonts/InterVariable-Italic.ttf", weight: "100 900", style: "italic" },
  ],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    default: "Release Flight",
    template: "%s · Release Flight",
  },
  description:
    "Editorial control surface for App Store Connect and Google Play — multi-tenant metadata, screenshots, previews and ASO intelligence.",
  applicationName: "Release Flight",
  // Icon is generated by app/icon.tsx — no static /favicon.ico needed
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#faf8f2" },
    { media: "(prefers-color-scheme: dark)", color: "#161614" },
  ],
  width: "device-width",
  initialScale: 1,
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>): Promise<JSX.Element> {
  // CSP nonce minted per-request by the middleware. The inline theme script
  // below MUST carry it or the strict (no 'unsafe-inline') production CSP blocks it.
  const nonce = (await headers()).get("x-nonce") ?? undefined;
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${inter.variable}`}
    >
      <head>
        <script
          nonce={nonce}
          // React strips the nonce from the client payload for security, so the
          // server-rendered nonce attribute "mismatches" the client's empty one.
          // The script already ran (in <head>, pre-hydration) under the correct
          // nonce — the mismatch is benign, so suppress the hydration warning.
          suppressHydrationWarning
          // Avoid FART (Flash of inacuRate Theme) — read theme synchronously
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem('gp-theme');if(t==='light'||t==='dark'){document.documentElement.setAttribute('data-theme',t);}}catch(e){}})();`,
          }}
        />
      </head>
      <body className="min-h-full bg-[var(--surface-paper)] text-[var(--ink-primary)] antialiased">
        <a href="#main-content" className="skip-link">
          Skip to content
        </a>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
