#!/usr/bin/env bash
#
# Release Flight — Community Edition · one-command self-host installer.
#
# Builds the web/worker/migrate images from source, generates a hardened .env
# with fresh random secrets, brings up the full stack (Postgres + Redis + MinIO),
# runs migrations + RLS + the owner bootstrap, and waits until the app is healthy.
#
# Re-running is safe: an existing .env is reused (secrets are NOT regenerated),
# and the migrate step is idempotent.
#
# Usage:
#   ./scripts/install.sh
#   OWNER_EMAIL=you@example.com OWNER_PASSWORD='…' ./scripts/install.sh
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SELFHOST="$ROOT/deploy/self-host"
COMPOSE="$SELFHOST/docker-compose.yml"
ENV_FILE="$SELFHOST/.env"

c() { printf '\033[%sm%s\033[0m\n' "$1" "$2"; }
info() { c "1;34" "→ $1"; }
ok() { c "1;32" "✓ $1"; }
die() { c "1;31" "✗ $1"; >&2 echo; exit 1; }

# ── Preflight ────────────────────────────────────────────────────────────────
command -v docker >/dev/null 2>&1 || die "Docker is not installed. Get it at https://docs.docker.com/get-docker/"
docker info >/dev/null 2>&1 || die "Docker daemon is not running. Start Docker and retry."
docker compose version >/dev/null 2>&1 || die "Docker Compose v2 is required (the 'docker compose' subcommand)."
command -v openssl >/dev/null 2>&1 || die "openssl is required to generate secrets."

cd "$ROOT"
mkdir -p "$SELFHOST/data/secrets" "$SELFHOST/data/storage" "$SELFHOST/data/license"

# ── Generate .env (once) ─────────────────────────────────────────────────────
GENERATED_OWNER=0
if [ -f "$ENV_FILE" ]; then
  info "Reusing existing $ENV_FILE (secrets unchanged)."
  OWNER_EMAIL="$(grep -E '^SELF_HOST_OWNER_EMAIL=' "$ENV_FILE" | cut -d= -f2- || true)"
else
  info "Generating .env with fresh secrets…"
  rnd() { openssl rand -base64 36 | tr -d '/+=' | cut -c1-32; }
  hex() { openssl rand -hex 32; }

  PG_PW="$(rnd)"
  APP_DB_PW="$(rnd)"
  MINIO_USER="rf_$(openssl rand -hex 4)"
  MINIO_PW="$(rnd)"
  OWNER_EMAIL="${OWNER_EMAIL:-owner@example.com}"
  OWNER_PASSWORD="${OWNER_PASSWORD:-$(rnd)}"
  GENERATED_OWNER=1

  umask 077
  cat > "$ENV_FILE" <<EOF
# Release Flight self-host — generated by scripts/install.sh. Keep this file secret.
DEPLOY_MODE=self_host
NODE_ENV=production
APP_URL=http://localhost:3000
APP_NAME=Release Flight
LOG_LEVEL=info

# Postgres (service name 'postgres', database 'gp')
POSTGRES_PASSWORD=$PG_PW
GP_APP_DB_PASSWORD=$APP_DB_PW
DATABASE_URL=postgresql://gp_app:$APP_DB_PW@postgres:5432/gp?schema=public&connection_limit=10&pool_timeout=10
DIRECT_URL=postgresql://gp:$PG_PW@postgres:5432/gp?schema=public
DATABASE_URL_ADMIN=postgresql://gp:$PG_PW@postgres:5432/gp?schema=public

# Redis
REDIS_URL=redis://redis:6379

# Object storage (MinIO, service name 'minio')
MINIO_ROOT_USER=$MINIO_USER
MINIO_ROOT_PASSWORD=$MINIO_PW
S3_ENDPOINT=http://minio:9000
S3_REGION=us-east-1
S3_BUCKET=releaseflight
S3_ACCESS_KEY_ID=$MINIO_USER
S3_SECRET_ACCESS_KEY=$MINIO_PW
S3_FORCE_PATH_STYLE=true

# Secrets at rest (AES-256-GCM) + signed storage URLs
SECRET_PROVIDER=filesystem
SECRETS_DIR=./data/secrets
SECRETS_ENCRYPTION_KEY=$(hex)
STORAGE_DIR=./data/storage
STORAGE_SIGNING_SECRET=$(rnd)$(rnd)

# Session
SESSION_SECRET=$(rnd)$(rnd)
SESSION_COOKIE_NAME=gp_session
SESSION_TTL_DAYS=7

# First-boot owner account (you'll be forced to change the password on first login)
SELF_HOST_OWNER_EMAIL=$OWNER_EMAIL
SELF_HOST_OWNER_PASSWORD=$OWNER_PASSWORD
EOF
  chmod 600 "$ENV_FILE"
  ok "Wrote $ENV_FILE (chmod 600)."
fi

# ── Build images from source ─────────────────────────────────────────────────
info "Building images from source (first run takes a few minutes)…"
docker build -f apps/web/Dockerfile    --target runtime -t marquee-web:local     .
docker build -f apps/web/Dockerfile    --target build   -t marquee-migrate:local .
docker build -f apps/worker/Dockerfile --target runtime -t marquee-worker:local  .
ok "Images built."

# ── Bring up the stack ───────────────────────────────────────────────────────
info "Starting the stack (postgres, redis, minio, migrate, web, worker)…"
docker compose -f "$COMPOSE" --project-directory "$SELFHOST" up -d

# ── Wait for health ──────────────────────────────────────────────────────────
info "Waiting for the app to become healthy at http://localhost:3000 …"
for i in $(seq 1 60); do
  if curl -fsS http://localhost:3000/api/v1/readyz >/dev/null 2>&1; then
    READY=1; break
  fi
  sleep 3
done

echo
if [ "${READY:-0}" = "1" ]; then
  ok "Release Flight is up → http://localhost:3000"
else
  c "1;33" "⚠ The app didn't report healthy within the timeout. Check logs:"
  echo "    docker compose -f $COMPOSE --project-directory $SELFHOST logs -f web migrate"
fi

echo
c "1;36" "Sign in:"
echo "  Email:    ${OWNER_EMAIL:-owner@example.com}"
if [ "$GENERATED_OWNER" = "1" ]; then
  echo "  Password: $OWNER_PASSWORD"
  c "1;33" "  (You'll be asked to change this on first login. It's also in $ENV_FILE.)"
else
  echo "  Password: (as set in $ENV_FILE)"
fi
echo
echo "Manage the stack:"
echo "  docker compose -f $COMPOSE --project-directory $SELFHOST [ps|logs -f|down]"
